### ISSUE TITLE
[Triage] Shorts not filtered properly

### ISSUE THREAD

**Issue by kieric82** [kieraneglin/pinchflat#433] opened 2024-10-24 17:43 UTC
As requested below the switch button.

I'm reporting an issue since the TV Shows Preset didn't filter out shorts videos from the source Dude Perfect. They get downloaded like the regular videos.

Please reach out if need anything.

**To Reproduce**

Add Dude Perfect source with TV Shows preset.

**Expected behavior**
No shorts videos.

**Screenshots**
Here's the Raw Attributes of the source.
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/10587a9b-5c78-4c9e-b8d8-ac22de72ff55">

**Diagnostic info**
- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: America/Toronto

**Comment by kieraneglin** [comment] 2024-10-24 17:47
Hey there! Thanks for the report (:

Thank you for the details! I'm going to close this as a duplicate of #415. tl;dr is that YouTube is making some changes for certain users it's causing yt-dlp to not return certain bits of data that I use to determine if something's a short.

Since this is only impacting some users, I haven't been able to reliably reproduce this issue. If you're willing, it would really help if you tried [updating yt-dlp](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#how-do-i-update-yt-dlp-independently-from-pinchflat) and seeing if the issue persists!

**Closed by kieraneglin** 2024-10-24 17:47 UTC
Labels: triage
