### ISSUE TITLE
[FR] Embbed Chapters

### ISSUE THREAD

**Issue by apolo-damasco** [kieraneglin/pinchflat#455] opened 2024-11-04 11:25 UTC
Is your feature request related to a problem? Please describe.
When downloading YouTube videos with chapters, the chapter information is lost in the exported file. This means users have to manually recreate chapters in their video players or editing software, which is time-consuming and prone to errors, especially for longer videos with many chapters.
Describe the solution you'd like
Add the ability to preserve and embed the original YouTube chapters as chapters/markers in the exported video file. The chapter timestamps and titles should be copied from the source YouTube video and embedded into the downloaded file's metadata in a format compatible with common video players (like VLC, MPV) and editing software.
Describe alternatives you've considered

Manually creating a separate chapter file (.txt or .cue)
Using external tools to extract and re-embed chapters after download
Writing a script to scrape chapter information from YouTube and inject it into the video file separately

Additional context
Many educational videos, podcasts, and long-form content use chapters extensively for navigation. Preserving this information would maintain the same user experience as the original YouTube video. Several video container formats (like MP4 and MKV) support chapter metadata, so this should be technically feasible to implement.

**Comment by kieraneglin** [comment] 2024-11-05 00:11
Hey there! Thanks for the report (:

The app uses the `--embed-metadata` flag which _should_ embed chapters if they exist. According to yt-dlp: `Embed metadata to the video file. Also embeds chapters/infojson if present unless --no-embed-chapters/--no-embed-info-json are used`. I've tested this myself and confirmed it seems to work. Here's the command I used and I've also included a screenshot from VLC: `ffprobe -show_chapters -of json "<VIDEO FILENAME HERE>"`

Would you mind confirming that the files don't have chapter data embedded but the YouTube video itself does? If that's the case, can you share an example YouTube video where you see this behaviour? Thanks!

![Screenshot 2024-11-04 at 4 06 52 PM](https://github.com/user-attachments/assets/09e00c3f-ee7d-487b-bd45-507e7bc5bc1b)

**Comment by kieraneglin** [comment] 2024-11-07 18:40
Closing this since further testing indicates that this works as expected when `Embed Metadata` is enabled. if you're still having trouble, feel free to re-open this issue or create a new one!

**Closed by kieraneglin** 2024-11-07 18:40 UTC
Labels: feature request

**Comment by prima-ram** [comment] 2024-11-07 19:00
I wasn't aware of this feature. I haven't had time to test it but I am sure it works. 

Thank you for the help.
