### ISSUE TITLE
[Triage] Slow indexing stops fast/rss indexing???

### ISSUE THREAD

**Issue by lukecrawford1997** [kieraneglin/pinchflat#425] opened 2024-10-21 22:50 UTC
**Describe the bug**
From what i can gather, it seems like when a channel is 'slow indexing', it dosnt update when new videos go live

**To Reproduce**
This is a hard one. I have tried this on a fresh install 3 times. it just seems that when i load all the sources from scratch, a random one or 2 gets stuck on slow indexing and dosnt update the new videos

**Expected behavior**
Slow indexing to happen in the background and for either rss or fast indexing to work along side it

**Screenshots**

![2024-10-21_23-43](https://github.com/user-attachments/assets/a33631ad-242f-40eb-a1ea-92df30f758b6)

**Diagnostic info**

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: Europe/London

**Additional context**

[pinchflat-logs-2024-10-21.txt](https://github.com/user-attachments/files/17467575/pinchflat-logs-2024-10-21.txt)

So like i said earlier, i have done 3 fresh installs of pinchflat to see if the problem will go away, it hasnt. I seem to have to restart pinchflat to get the slow indexing to work and that will pick up the new videos. i dont know of another way to get it sorted otherwise.

The thing that confuses me the most, i have left it for 5 days so far. All the other sources work fine, its just a couple that seem to get stuck, and i have no idea why. And just for reference, the two channels that seems stuck right now are 'linus tech tips' and 'nile red'.

Also, the recent restart is a manual one. I wanted to see if the new videos that the channel uploaded got downloaded. They did. I also dont know whats happening with the fast indexing on the screenshot, its mainly there to show the two slow indexing.

Any help would be appreciated. Thanks in advance

**Comment by kieraneglin** [comment] 2024-10-22 17:32
Hey there! Thanks for the report (:

You're correct in saying that fast indexing passes don't run while a slow-indexing pass is in-progress. I initially did this for a reason, but I can't remember _why_ since I apparently didn't document it 🙃. I'll look into this again and see if I can implement that or if I remember why I initially made that choice. 

The errors and job failures you're seeing are a separate issue and I actually think these are the symptom of another problem. I'm seeing a few database timeouts in your logs and these are causing jobs to fail. This is _extremely_ odd for normal setups, so I'd like to know more about how you're storing your Pinchflat config. Is it on your local disk or a network share? Is it on an SSD or an HDD?

**Comment by lukecrawford1997** [comment] 2024-10-23 12:41
Hi, 

Thanks for the reply. If thats intended, fair enough, it just seemed like something that would happen to not miss out on channels with large amounts of videos.

So basically, and this is sods law, ive had this trouble for 2 weeks, over 3 installations. Its suddenly fixed itself and their is no longer any jobs pending.......

Though i do have a couple questions. To answer your question though, the config folder is on a hdd. Is it possible that the timeouts are caused by a spin up delay and that is causing the indexing to fail. If so, do you reckon changing the config file to a ssd will fix the issue should it arise again. i only put them on a local hdd so that downloads and config were together, but i can change that if itll help in the future

**Comment by kieraneglin** [comment] 2024-10-24 20:32
I misspoke! There are a few cases in which fast indexing doesn't run during slow indexing (like when you first create a source). In normal operation past that point they will run concurrently for the most part.

I see the issue is has come back. I would try putting the config on your SSD and also performing some sort of health check on your HDD. I saw a lot of errors in your logs that indicate that the attempt to save data to the database timed out and that's not normal under regular usage. This is also the first time I've gotten a report for an error like this so I don't suspect it's widespread

**Comment by lukecrawford1997** [comment] 2024-10-25 22:55
Thanks for the reply.

Ive done as you said and restarted the container, and so far so good. It does seem to be a hdd error as im getting a warning for start/stop count. May be related as thats the only thing i can think of. 

I can leave it up for a few days and see how it goes, or you can close this for now. It does seem to be my specific hdd thats the problem right now, but i can let you know in a few days to see if its sorted if you like.

**Comment by kieraneglin** [comment] 2024-10-26 17:05
Glad to hear it seems to be working! I'll close this issue, but if you see trouble again feel free to either open a new one or reopen this one 🤙🏻

**Closed** 2024-10-26 17:05 UTC
Labels: triage
