### ISSUE TITLE
Trouble with Jellyfin accepted filepath creation

### ISSUE THREAD

**Issue by LoganJFisher** [kieraneglin/pinchflat#167] opened 2024-04-06 00:09 UTC
I've followed [these instructions](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions), but I can't seem to get the Youtube videos I'm downloading to actually organize nicely within Jellyfin. They appear, but the folder structure isn't being respected.

---

### When looking at TV shows I have, the structure is:

For the show's collection images:

    [Show]\[name].png

> [name] is backdrop, folder, and logo

For a season's poster:

    [Show]\Season ##\folder.png

For a season's episode images:

    [Show]\Season ##\metadata\[Show] - S##E## - [EpisodeTitle].png

For the episodes:

    [Show]\Season ##\[Show] - S##E## - [EpisodeTitle].mkv

---

### In contrast, when looking at the videos downloaded by Pinchflat, the structure is:

For the show's collection images:

    [Show]\[name].png

> [name] is banner, fanart, and poster

For a season's poster:

    N/A

For a season's episode images:

    [Show]\Season ####\[Show] [S####E####] [EpisodeTitle].jpg

For the episodes:

    [Show]\Season ####\[Show] [S####E####] [EpisodeTitle].mp4

---

I'm not sure if I'm doing anything wrong or if Jellyfin is just particularly picky and Pinchflat needs some sort of update to accommodate. In either case, help would be appreciated. Thank you.

**Comment by LoganJFisher** [comment] 2024-04-06 00:10
For reference, here is the Jellyfin documentation on show naming schema: https://jellyfin.org/docs/general/server/media/shows/

**Comment by kieraneglin** [comment] 2024-04-06 03:21
Hey there! Thanks for the report (:

If you look at the "Images" section on the documentation you linked, Pinchflat follows that convention if possible generating a banner image, fan art image, and poster image. I found these are the image names that work best with the possible images returned from YouTube. 

By any chance, are you trying to download a playlist? Unfortunately series-level images only work for channels since playlists don't have any sort of banner art and, by extension, I can't add any series images for playlists. I've tried to think through a way to approach this (like grabbing the image metadata for the first entry in the playlist), but in all of my testing that approach made things quite confusing in practice. 

If you aren't using a playlist and this issue is coming from a channel, please pass on your settings for the media profile as well as the channel URL and I'll do my best to try and replicate it!

**Comment by LoganJFisher** [comment] 2024-04-06 03:29
Sorry, I may have been unclear. My focus isn't just on the images specifically, but the file structure as a whole. I believe due to some quark of naming schema, Jellyfin is just detecting each individual episode and dumping them all into my "Videos" category individually rather than bundled under a single "show" (channel).

I'm trying to do full-channels. My test case has been [A Capella Science](https://www.youtube.com/channel/UCTev4RNBiu6lqtx8z1e87fQ).

No -thumb on anything I see.

---


    id: 1
    name: Videos
    inserted_at: 2024-04-05T22:42:58Z
    updated_at: 2024-04-05T23:37:40Z
    output_path_template: /Videos/{{ source_custom_name }}/Season {{ season_from_date }}/{{ source_custom_name }} {{ season_episode_from_date }} {{ title }}.{{ ext }}
    preferred_resolution: 1080p
    sponsorblock_categories: sponsor, intro, outro, selfpromo, preview, interaction
    sponsorblock_behaviour: remove
    download_thumbnail: true
    embed_thumbnail: true
    download_auto_subs: false
    download_subs: true
    embed_subs: true
    sub_langs: en
    download_metadata: false
    embed_metadata: true
    download_source_images: true
    download_nfo: true
    livestream_behaviour: exclude
    shorts_behaviour: exclude

**Comment by kieraneglin** [comment] 2024-04-06 03:43
My apologies - I missed a sentence in the original post and it totally changed the meaning in my head. That's what I get for rushing 😅

Anyway, thank you again for the report!  I'll look into this more deeply over the weekend or early next week

**Comment by LoganJFisher** [comment] 2024-04-06 03:47
Thanks!

I'll be very busy over the next three days, so if you need any more info or for me to try anything, I may be a bit slow on the response.

**Comment by kieraneglin** [comment] 2024-04-06 03:49
I'm not certain this will do much but could you try flipping the script on the title/season order:

```
/Videos/{{ source_custom_name }}/Season {{ season_from_date }}/{{ season_episode_from_date }} - {{ title }}.{{ ext }}
```

This is the combo I've had the best luck with 🤞🏻

**Comment by LoganJFisher** [comment] 2024-04-06 04:25
Nope. Same result.

**Comment by kieraneglin** [comment] 2024-04-06 17:14
One more thing - did you enable NFO files? That might be the ticket

**Comment by kieraneglin** [comment] 2024-04-06 20:53
Fixed! Try updating to the latest version and re-downloading with NFO files if you haven't already. If you didn't download NFO files in the first place, you will have to delete the source + files and re-add the source after enabling NFO generation

**Comment by LoganJFisher** [comment] 2024-04-10 03:54
Ah. I hadn't enabled NFO for file format for my library in Jellyfin. If that's written somewhere as something I needed to do, I totally missed it.

It is enabled in the media profile for Pinchflat.

Despite that, they're still not automatically sorting into a single "show". I also tried switching to [a different Youtube channel](https://www.youtube.com/channel/UCNIuvl7V8zACPpTmmNIqP2A) just in case there was some issue unique to that other channel for whatever reason. The issue persists.

**Comment by kieraneglin** [comment] 2024-04-10 16:45
NFO support within Jellyfin should be automatically enabled and, in fact, cannot be disabled ([source](https://jellyfin.org/docs/general/server/metadata/nfo/#reading-metadata-from-nfo-files)). There shouldn't be any additional steps required on the Jellyfin side.

I'm away from my server for a week (and I'm just learning my VPN is busted so I can't remote in). That said, I asked someone to test it for me with these parameters:

- An output template of `/shows/{{ source_custom_name }}/Season {{ season_from_date }}/{{ title }} - {{ season_episode_from_date }}.{{ ext }}`
- `Download NFO data` and `Download Series Images` is enabled in the media profile
   - Their media profile is essentially the same as the "Media Center" preset
- They added a new source that uses the correct media profile and tracks `https://www.youtube.com/@OverSimplified`

With these settings, everything works as expected:

![JellyfinMediaPlayer_WvOc9xYZSX](https://github.com/kieraneglin/pinchflat/assets/569917/13e8314d-ad5e-4c65-9329-2c466e55b0b0)

---

I won't be able to provide much more meaningful support until I get back home and can test on my server, but I suspect there's some other issue at play here.  Thank you @tiritibambix for helping me test!

**Comment by LoganJFisher** [comment] 2024-04-10 16:50
Okay, I'm doing a bit of testing about, and it seems that "Music Videos" is the Jellyfin library type that seems to work best for Youtube videos. The ideal file structure seems to be: [Channel Name] and then individual folders not for seasons, but rather for individual episodes. In that folder should be the video and at least a folder.jpg, but a backdrop.jpg is also good to have. I'm not sure what structure would work best for channels that actually have a season-based structure.

That seems to work with just one oddity: the metadata for the year is a bit screwy. For example, a video made on January 31, 2020 has its year as "20200131" rather than just "2020".

**Comment by LoganJFisher** [comment] 2024-04-10 16:52
Oh, and I'm not actually getting the channel image. Instead, it's just using the image from one of the videos.

**Comment by LoganJFisher** [comment] 2024-04-10 17:23
I did try that, but music videos just seems to work better. I can't really explain why.

**Comment by kieraneglin** [comment] 2024-04-16 23:54
Closing since I am _very_ confident that this is an issue with usage or with Jellyfin. Here is what I tested:

1. I setup JF from scratch and created a new Pinchflat source using the Media Center preset. Everything worked correctly first try
2. I've asked others to do the same and they reported no issue
3. Based on #183, I'm 100% confident that either NFO files weren't written to disk _by Pinchflat_ or there's an issue with Jellyfin's internal representation of metadata. Looking [here](https://github.com/jellyfin/jellyfin/blob/c1fc80e85eb547311e6215dabe567678b8c5906b/MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs#L519), the date information is preferentially pulled from the date-related fields in the NFO file (in our case, `aired`). That field is known to be well-formed and the only way it would not be used is if that field isn't present in the NFO. After that, it falls back to either the filepath or the file metadata to try and discern the creation date which is what was seen in #183.

That said, I have a hunch that JF keeps some internal metadata that sticks around independent of the local file. I'm not sure how to prove this, but regardless it's an issue with JF and outside the scope of this app.

---

I appreciate the report! I'll happily re-open if this issue can be reproduced with the following constraints:

- The default Media Center preset is used
- The example Source is one that's never been used on Jellyfin

**Closed by kieraneglin** 2024-04-16 23:54 UTC
