### ISSUE TITLE
Pinchflat not working anymore after update. Internal Server Error

### ISSUE THREAD

**Issue by shaunvis1** [kieraneglin/pinchflat#450] opened 2024-11-02 12:05 UTC
**Describe the bug**
I updated my docker and now get "Internal Server Error"

**To Reproduce**

1. Start Pinchflat, go to homepage

**Expected behavior**

**Screenshots**

**Diagnostic info**

**Status**:
`500`

**Reason**:
`%Exqlite.Error{message: "database disk image is malformed", statement: "SELECT count(m0.\"id\") FROM \"media_items\" AS m0 WHERE (NOT (m0.\"media_filepath\" IS NULL))"}`

**Stacktrace**:
```
    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:1078: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:976: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.3) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.12.3) lib/ecto/repo/queryable.ex:162: Ecto.Repo.Queryable.one!/3
    (pinchflat 2024.10.30) lib/pinchflat_web/controllers/pages/page_controller.ex:30: PinchflatWeb.Pages.PageController.render_home_page/1
    (pinchflat 2024.10.30) lib/pinchflat_web/controllers/pages/page_controller.ex:1: PinchflatWeb.Pages.PageController.action/2
    (pinchflat 2024.10.30) lib/pinchflat_web/controllers/pages/page_controller.ex:1: PinchflatWeb.Pages.PageController.phoenix_controller_pipeline/2

```
  
[pinchflat-logs-2024-11-02.txt](https://github.com/user-attachments/files/17606809/pinchflat-logs-2024-11-02.txt)

**Additional context**

**Comment by kieraneglin** [comment] 2024-11-04 23:33
Hey there - thanks for the report!

This isn't an issue with Pinchflat per se, but rather an issue with SQLite itself. This can be caused by any number of things, but common ones include:

- storing the database on a networked file share without disabling the WAL
- storing the database on an NFSv3 share, or;
- moving around the database while it's being written to

See more [here](https://www.sqlite.org/faq.html#q21). This can happen with any sqlite-backed app including things like Sonarr/Radarr, but let's see about getting that fixed.

---

**Possible fix for SQLite error:**
1. Stop the Pinchflat Docker container
2. On your host machine, navigate to the directory that holds your Pinchflat config. You should see that there's a folder called `db`. Back up this folder before continuing.
3. Once backed up, open terminal on your host and navigate to the `db` directory that was the source of the backup you just created. For me, that looks like `cd /appdata/pinchflat/db`
4. Install the sqlite CLI. This will vary depending on your distro, but it's usually something like `sudo apt install sqlite3`
5. Run these commands (adapted from [this](https://stackoverflow.com/a/5316540/5665799) SO answer):
```
mv pinchflat.db pinchflat_bak.db
mv pinchflat.db-shm pinchflat_bak.db-shm 2>/dev/null
mv pinchflat.db-wal pinchflat_bak.db-wal 2>/dev/null

echo '.recover' | sqlite3 pinchflat_bak.db | sqlite3 pinchflat.db
```
6. Re-start the Pinchflat Docker container and see if everything's working again

---

Let me know if you have any questions!

**Comment by kieraneglin** [comment] 2024-11-14 23:52
Closing. If you're still having trouble, feel free to re-open!

**Closed by kieraneglin** 2024-11-14 23:52 UTC
Labels: triage
