### ISSUE TITLE
[Triage] Names being changed to "youtube video #xxx" and not saving posters or images?

### ISSUE THREAD

**Issue by Lizzardis** [kieraneglin/pinchflat#390] opened 2024-09-13 22:11 UTC
**Describe the bug**
PinchFlat can be working perfectly for a while, but then for some reason, all of the downloaded files in the UI are then labelled "youtube video #xxxx" - Alongside this, it appears that the posters for the channels are not being downloaded and the videos themselves also don't have a "poster" or an image either when viewing them in Plex?

If I were to delete the whole container including downloaded files, and then repull the image & recreate the container and redownload everything, it would work as expected. For some reason, this just seems to happen?

**To Reproduce**
Unsure, it seems to happen when clearing up old images from Docker?

**Screenshots**
![Screenshot 2024-09-13 230439](https://github.com/user-attachments/assets/9f478bf4-b8f0-4629-abcb-134685c551a6)

**Diagnostic info**

- App Version: 2024.9.12
- yt-dlp Version: 2024.08.06
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: UTC

**Additional context**

[pinchflat-logs-2024-09-13(1).txt](https://github.com/user-attachments/files/16999756/pinchflat-logs-2024-09-13.1.txt)

**Comment by kieraneglin** [comment] 2024-09-16 16:35
I've checked with the `yt-dlp` team and they've confirmed it's an issue on their end rather than with Pinchflat. That said, they're also _very_ curious as to what's causing this issue since it's not one they've seen recently. If you're game, we'd both really appreciate if you ran the following troubleshooting steps:

1. Open a Pinchflat console and enter `su`
2. Once that's done, copy and paste this whole block:

```
apt-get update
apt-get install zip -y
mkdir /tmp/yt-dlp-test && cd $_
yt-dlp https://www.youtube.com/watch?v=cBG2S8FW5KM --simulate --skip-download --ignore-no-formats-error --no-warnings --print-to-file "%(.{id,title,live_status,webpage_url,description,aspect_ratio,duration,upload_date,timestamp,playlist_index})j" output.json --windows-filenames --quiet --cache-dir /tmp/pinchflat/data/yt-dlp-cache --write-pages
zip -r yt-dlp-test.zip .
```

This will create a zip file with all the test data they need. Then, you can optionally move the zip file to, say, your downloads directory to make it easier to get at: `cp /tmp/yt-dlp-test/yt-dlp-test.zip /downloads/yt-dlp-test.zip`

If you could then attach that zip file to this issue that would be extremely helpful!

**Comment by Lizzardis** [comment] 2024-09-17 15:57
Well that was fun! I can honestly say I've never moved files in & out of a container before via command line, I usually just set the volumes in docker / portainer and never play with them again. I appreciate the step by step guidance. Worked a treat!

I also appreciate you reaching out to the yt-dlp team as well. Hopefully they get some answers. If they don't, feel free to get back to me and I'll do what I can to help.

The Zip file you requested is below:
[yt-dlp-test.zip](https://github.com/user-attachments/files/17031573/yt-dlp-test.zip)

**Comment by kieraneglin** [comment] 2024-09-18 17:08
Thank you for that! Unfortunately, it doesn't contain the information we need since, as you saw, everything appears to be working again.

There's been no push to Pinchflat or yt-dlp - transient issues like this are from YouTube making changes behind-the-scenes and I guess you were one of the first to get some new experiment they were running. The yt-dlp team is usually pretty quick to make updates once they have some examples of YouTube's changes, but I guess this one didn't stick around for long enough

I'm going to close this issue since everything seems like it's working, but please re-open it if you see it again! In fact, if you see it and you can run those troubleshooting steps above to get another zip file that could help out the `yt-dlp` team a lot!

Thanks again (:

**Closed by kieraneglin** 2024-09-18 17:08 UTC
Labels: triage
