### ISSUE TITLE
[FR] Support for different codecs in the UI

### ISSUE THREAD

**Issue by moostmartijn** [kieraneglin/pinchflat#392] opened 2024-09-17 18:25 UTC
**Is your feature request related to a problem? Please describe.**
Finally a working solution for downloading YouTube videos automatically! Initially I was very happy, but after setting everything up and watching the first downloaded video's on my TV, I encountered a problem; the VP9 codec needs transcoding and my server can't handle it. Even small videos needs buffering unfortunately. 

Samsung Smart TV 2021
Synology DS923+

**Describe the solution you'd like**
I'm not sure if it is even possible with yt-dlp, but within Pinchflat I would like to see an option to change codecs... The .mp4 container is fine, so no need for .mkv, it's just the codec that has a problem playing directly from Plex to my TV. So .mp4 with hevc / h.264 would be perfect. I don't care much about the extra processing time per video download.

See the documentation of Plex for the Samsung TV: https://support.plex.tv/articles/203810286-what-media-formats-are-supported/

In this documentation they say the VP9 codec is fine with .mkv files, but I guess the metadata is not written to this container / Plex can't read the metadata in a .mkv container (?)

I would love to see a kind of drop-down menu (in the advanced editing mode) to choose a different codec and/or container

**Describe alternatives you've considered**
I have my fingers crossed that someone comes up with a working solution for my problem, I guess I won't be the only one encountering this problem. If not I gues yt-dlp is not an option for me. 

Anyway, keep up the good work with your application, I like it!

**Comment by kieraneglin** [comment] 2024-09-18 17:14
Hey there! Thanks for the report (:

There is an option for this, but it's a global option for all videos. Could you try going into Config > Settings and enable advanced mode (upper right)? If you do that, you'll be able to set a preferred codec. Note that this is just a _preference_ and `yt-dlp` will download what it determines to be the next-best if your codec of choice isn't available

**Comment by moostmartijn** [comment] 2024-09-20 09:10
Thanks for your reply, I totally missed the option to set a codec in the settings.

I noted that initially the codec was set as `avc`  while this is not een option for `yt-dlp` (?), I found this on their Github page: `vcodec: Video Codec (av01 > vp9.2 > vp9 > h265 > h264 > vp8 > h263 > theora > other)`

I tried the following options; `h265`, `h264` and `hevc` (which is not in the list), but unfortunately it keeps downloading with the `VP9` codec. 

Is there another way to force it to download a video with the `h265` codec if available and fallback to the `h264` codec?

**Comment by kieraneglin** [comment] 2024-09-24 22:28
Sorry, I missed this reply somehow!

It's confusing, but there is indeed (barely documented) support for an `avc` option [here](https://github.com/yt-dlp/yt-dlp/blob/4a9bc8c3630378bc29f0266126b503f6190c0430/yt_dlp/utils/_utils.py#L5284). The reason I went with that in the first place is that it's shown in the README [here](https://github.com/yt-dlp/yt-dlp/blob/4a9bc8c3630378bc29f0266126b503f6190c0430/README.md?plain=1#L1554).

If I recall `avc` should actually prefer h264 above all else (h265 isn't available on youtube IIRC). yt-dlp only allows you to choose one codec as the highest priority, but not pick a custom order. Unfortunately it sounds like the video you want is not available in h264 at the given resolution.

If you want to be sure, you can run `yt-dlp <video URL> --list-formats` and send a screenshot of the table it outputs

**Comment by moostmartijn** [comment] 2024-09-26 18:41
Thanks alot for your reply. Actually it does download some videos in h264 except for one channel, so I guess it works. 

I did a check on a video of the channel that does not download in h264, and it is indeed not available unfortunately:
<img width="946" alt="Scherm­afbeelding 2024-09-26 om 20 39 20" src="https://github.com/user-attachments/assets/453f05a5-036d-477a-aa4a-1dc93d0a215a">

I think I will let tdarr transcode the videos in h264.

**Comment by kieraneglin** [comment] 2024-09-26 19:45
Well, it's a little nice to hear that things were working as intended, even tough it's annoying that the codecs provided by YouTube aren't consistent

I'll close this issue but if something comes up please feel free to re-open it or make a new one!

**Closed by kieraneglin** 2024-09-26 19:45 UTC
Labels: feature request

**Comment by michaelborn** [comment] 2024-10-17 08:44
@moostmartijn FWIW, here are the settings I used to fix the video play on my Samsung 4k TV:

Under Config->Settings:
* Video codec: `VP9`
* Audio codec: `aac`

Under the Media Profile:
* Media Container: mkv

What I've found is that Samsung does not support the Opus audio codec in an mp4 container. There was also some issue with the mp4 container, though I couldn't figure out exactly what. Switching to a `.mkv` file/container seems to have solved the problem.

![image](https://github.com/user-attachments/assets/c5768a2f-7664-4e4f-a907-7217124896a7)
![image](https://github.com/user-attachments/assets/ef2cd5e7-fb16-4a23-8568-98f581878fac)

**Comment by moostmartijn** [comment] 2024-10-17 09:12
Thanks, I can try this. But… I do use Plex and read that changing the container to .mkv creates some problems with the metadata, because a .mkv container can’t store metadata. Is that correct / do you have this problem?

**Comment by kieraneglin** [comment] 2024-10-21 17:14
@moostmartijn it's true that Plex can't read metadata from MKV files. Plex seems to be planning to add NFO support which will solve a LOT of issues ([source](https://forums.plex.tv/t/plex-fireside-in-the-forum-2024/885879/319) - ctrl-f for "NFO"), but for now the only way to read metadata on the file itself in Plex is to use an MP4 container
